#!/bin/sh


while read local_ref local_sha remote_ref; do
  this_match="/tags"
  if [[ $local_ref =~ $this_match ]]; then
    git tag --sort=-creatordate | sed '1d' | xargs git tag -d \
     && git fetch origin && git push
     exit 1
  fi
done

exit 0
