#!/bin/sh

remote="$1"
url="$2"

echo '===start==='


while read local_ref local_sha remote_ref remote_sha; do
  echo "local_ref==="$local_ref
  echo "remote_ref==="$remote_ref
  this_match="/tags"
  if [[ $local_ref =~ $this_match ]]; then
    git tag --sort=-creatordate | sed '1d' | xargs git tag -d && git fetch origin
  fi
done

exit 0
